# Generated by Django 5.2.3 on 2025-07-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogposts',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('head0', models.CharField(max_length=5000)),
                ('chead0', models.CharField(max_length=5000)),
                ('head1', models.CharField(max_length=100)),
                ('chead1', models.CharField(max_length=5000)),
                ('head2', models.CharField(max_length=100)),
                ('chead2', models.CharField(max_length=5000)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
