# Generated by Django 5.2.3 on 2025-07-14 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='poducts_name',
            new_name='products_name',
        ),
    ]
